
title: Tak's Cover Letter
url: 'https://njir.github.io'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Hyungtak Jin
tagline: Junior Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: njirtak@gmail.com
website: njir.github.io
linkedin: hyungtak
github: njir

# Tracker
analytics: UA-46214266-2
#Update all the sections by editing the files inside _includes folder.
